### ISSUE TITLE
The "https://code.wireshark.org" can't be resolved error!

### ISSUE THREAD

**Issue by am1rzaei** [robvandenbrink/ouilookup#2]
Hi there,

I got introduced to your code from a book that I'm reading and wanted to give it a try. Once I ran ./oui.sh update, it gave an error that the URL https://code.wireshark.org cannot be resolved.

Based on [Wiresharks OUI Lookup Tool](https://www.wireshark.org/tools/oui-lookup.html), a new list of OUI's can be downloaded from https://www.wireshark.org/download/automated/data/manuf

I replaced the old URL with the new one in the script and it worked flawlessly.
Thought this would be helpful for you.

Thanks for your code!

**Comment by robvandenbrink** [comment]
Resolved - as you noted the download link was moved, updated in the script and we're good to go again.  thanks for the heads up!

**Comment by robvandenbrink** [comment]
as noted in previous comment, resolved
